config/routes.rb
Rails.application.routes.draw do

  resources :animals

  #generates /sightings/get_events route
    resources :sightings do
      get :get_events, on: :collection
    end


  root 'animals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :sightings, dependent: :destroy
  validates :common_name, :latin_name, :kingdom, presence:true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  belongs_to :animal
  validates :animal, :date, :time, :latitude, :longitude, presence:true
  
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    if @animal.sightings == []
      @animal.destroy
      respond_to do |format|
        format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
        format.json { head :no_content }
        
      end
    else
      @animals = Animal.all
      flash.now[:notice] = "Animal cannot be deleted! Sightings of this animal are stored."
      render 'animals/index.html.erb'
    end
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:common_name, :latin_name, :kingdom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]

  def get_events
    @sightings = Sighting.all
    events = []
    @sightings.each do |sighting|
      events << { title: sighting.animal.common_name, start: sighting.date.to_s + " " + sighting.time.strftime("%H:%M:%S"), url: Rails.application.routes.url_helpers.sighting_path(sighting.id) }
    end
    render :json => events.to_json
  end
  # GET /sightings
  # GET /sightings.json
  def index
    if params[:start_date].nil? && params[:end_date].nil?
      @sightings = Sighting.all
    else
      @sightings = Sighting.where(date: params[:start_date]..params[:end_date]).where(region: params[:region])
      render('sightings/index.html.erb')
    end
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
  end

  # GET /sightings/new
  def new
    @sighting = Sighting.new
      if params[:animal].nil?
        @sighting.animal = Animal.first
      else
        @sighting.animal = Animal.find(params[:animal])
      end
    @animals_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end
    @region = ['North', 'South', 'East', 'West']
    @region_for_select = @region.map do |region|
      [region, region]
    end
  end

  # GET /sightings/1/edit
  def edit
    @animals_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end
    @region = ['North', 'South', 'East', 'West']
    @region_for_select = @region.map do |region|
      [region, region]
    end
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(sighting_params)

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:date, :time, :latitude, :longitude, :region, :animal_id, :start_date, :end_date)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :common_name %>
    <%= form.text_field :common_name, id: :animal_common_name %>
  </div>

  <div class="field">
    <%= form.label :latin_name %>
    <%= form.text_field :latin_name, id: :animal_latin_name %>
  </div>

  <div class="field">
    <%= form.label :kingdom %>
    <%= form.text_field :kingdom, id: :animal_kingdom %>
  </div>

  <div class="actions">
    <%= form.submit id: :add_new_animal_button %>
  </div>
<% end %>

app/views/animals/_sighting.html.erb
<li>
  <%= link_to sighting.time.strftime("%H:%M").to_s + " " + sighting.date.strftime("%m/%d/%y").to_s, sighting %>
</li>

app/views/animals/edit.html.erb
<div class="content">


<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

</div>

app/views/animals/index.html.erb
<div class="content">

<p id="notice"><%= notice %></p>

<h1>Animal Tracker</h1>

<table>
  <thead>
    <tr>
      <th>Common name</th>
      <th>Latin name</th>
      <th>Kingdom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="animal_list">
    <% @animals.each do |animal| %>
      <tr >
        <td><%= animal.common_name %></td>
        <td><%= animal.latin_name %></td>
        <td><%= animal.kingdom %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>
<%= link_to 'Sightings', sightings_path %>
</div>


<p>
  <div class="field">
    <label for="animal_common_name">Common Name</label><br>
    <input type="text" name="animal[common_name]" id="animal_common_name" />
  </div>

  <div class="field">
    <label for="animal_latin_name">Latin Name</label><br>
    <input type="text" name="animal[latin_name]" id="animal_latin_name" />
  </div>

  <div class="field">
    <label for="animal_kingdom">Animal Kingdom</label><br>
    <input type="text" name="animal[kingdom]" id="animal_kingdom" />
  </div>

  <button id="add_new_animal_button">Add New Animal</button>
</p>


<%= image_tag("zebra.png", :alt => "zebra", :class => "animal", :id => "zebra") %>
<%= image_tag("penguin.png", :alt => "zebra", :class => "animal", :id => "penguin") %>
<%= image_tag("turtle.png", :alt => "zebra", :class => "animal", :id => "turtle") %>

app/views/animals/new.html.erb
<div class="content">


<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

</div>

app/views/animals/show.html.erb
<div class="content">

<p id="notice"><%= notice %></p>

<p>
  <strong>Common name:</strong>
  <%= @animal.common_name %>
</p>

<p>
  <strong>Latin name:</strong>
  <%= @animal.latin_name %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @animal.kingdom %>
</p>

<p>
  <strong>Sightings:</strong>
  <ul id="sighting_list">
    <%= render partial: "sighting", collection: @animal.sightings %>
  </ul>
</p>

<%= link_to 'New Sighting', new_sighting_path(:animal => @animal.id)%>
<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

</div>

<h3>Add new sighting:</h3>

<p>
  <div class="field">
    <label for="sighting_date">Date</label>
    <input id="sighting_date" name="sighting[date]" type="date">
  </div>
  <div class="field">
    <label for="sighting_time">Time</label>
    <input id="sighting_time" name="sighting[time]" type="time">
  </div>
  <div class="field">
    <label for="sighting_latitude">Latitude</label>
    <input type="text" name="sighting[latitude]" id="sighting_latitude" />
  </div>
  <div class="field">
    <label for="sighting_longitude">Longitude</label>
    <input type="text" name="sighting[longitude]" id="sighting_longitude" />
  </div>
  <div class="field">
    <label for="sighting_region">Region</label>
    <select id="sighting_region" name="sighting[region]">
      <option value="North">North</option>
      <option value="South">South</option>
      <option value="East">East</option>
      <option value="West">West</option>
    </select>
  </div>
  <input type="hidden" name="sighting[animal_id]" id="animal_id" value="<%=@animal.id%>"/>
  <button id="add_new_sighting_button">Add New Sighting</button>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery', 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/_form.html.erb
<%= form_with(model: sighting, local: true) do |form| %>
  <% if sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :sighting_date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time, id: :sighting_time %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :sighting_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :sighting_longitude %>
  </div>

  <div class="field">
      <%= form.label :region %>
      <%= select(:sighting, :region, @region_for_select) %>
  </div>

  <div class="field">
    <%= form.label :animal_id %>
    <%= select(:sighting, :animal_id, @animals_for_select) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/sightings/edit.html.erb
<div class="content">


<h1>Editing Sighting</h1>

<%= render 'form', sighting: @sighting %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

</div>

app/views/sightings/index.html.erb
<div class="content">


<p id="notice"><%= notice %></p>

<h1>Sightings</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Region</th>
      <th>Animal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.date.strftime("%m/%d/%y") %></td>
        <td><%= sighting.time.strftime("%H:%M") %></td>
        <td><%= sighting.latitude %></td>
        <td><%= sighting.longitude %></td>
        <td><%= sighting.region %></td>
        <td><%= sighting.animal.common_name %></td>
        <td><%= link_to 'Show', sighting %></td>
        <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
        <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sighting', new_sighting_path %>


<%= link_to 'Animals', animals_path %>
</div>


<h2>Filter by Date:</h2>

<form action="/sightings" method="get">
  <label for="start_date">Start date</label>
  <input id="start_date" name="start_date" type="date">
  <br>
  <br>
  <label for="end_date">End date</label>
  <input id="end_date" name="end_date" type="date">
  <br>
  <br>
  <select id="region" name="region">
    <option value="North">North</option>
    <option value="South">South</option>
    <option value="East">East</option>
    <option value="West">West</option>
  </select>
  <br>
  <br>
  <button>Run report</button>
</form>
<br>
<br>


<div id="calendar">
</div>

app/views/sightings/new.html.erb
<div class="content">

<h1>New Sighting</h1>

<%= render 'form', sighting: @sighting %>

<%= link_to 'Back', sightings_path %>

</div>

app/views/sightings/show.html.erb
<div class="content">


<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sighting.date.strftime("%m/%d/%y")  %>
</p>

<p>
  <strong>Time:</strong>
  <%= @sighting.time.strftime("%H:%M") %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sighting.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sighting.longitude %>
</p>

<p>
  <strong>Region:</strong>
  <%= @sighting.region %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @sighting.animal.common_name %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>

</div>